server {
    listen 80;
    server_name patch.zelusrsps.com;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name patch.zelusrsps.com;

    ssl_certificate     /etc/letsencrypt/live/patch.zelusrsps.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/patch.zelusrsps.com/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    root      /server/patch;
    autoindex off;

    location / {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=3600";
    }
}
